### ISSUE TITLE
Implementar pipelines para CI/CD no projeto.

### ISSUE THREAD

**Issue by B0nam** [KauanMuriel/marvel-nft#7]
Desenvolver pipelines para buildar, testar e publicar a aplicação.

Por meio das pipelines do github actions, desenvolver o seguinte fluxo de CI/CD:
- Gerar imagem docker com o banco de dados teste e homologação
  - Gerar imagem postgres
  - Iniciar dado testes no banco
  - Publicar nova imagem com os dados teste
- Gerar imagem docker nodeJS
  - Realiza a compilação
  - Realiza os testes (necessário rodar o banco de homologação)
  - Publicar nova imagem com a aplicação
  
  Obs: Se for utilizado um cluster node com mais de uma instancia da aplicação o fluxo deve ser alterado.

**Comment by B0nam** [comment]
Necessário adicionar chaves de acesso do dockerhub no repositorio.

**Comment by kauanrossii** [comment]
Chaves de acesso adicionadas no repositório.
